### ISSUE TITLE
openweather api call seems to happen twice

### ISSUE THREAD

**Issue by sammcgrail** [sammcgrail/radarplot#17]
<img width="1722" alt="Screenshot 2023-09-12 at 12 06 42 AM" src="https://github.com/sammcgrail/radarplot/assets/6109568/c2752d6f-afc2-4689-9be5-36bcbd93bb18">

I see reverse happening twice, and oncecall happening 4 times. If it's react strict mode, does this mean it was actually called twice? 

<img width="865" alt="Screenshot 2023-09-12 at 12 07 27 AM" src="https://github.com/sammcgrail/radarplot/assets/6109568/09b47d2d-a590-45c3-9e9a-d3013322e18b">

**Comment by sammcgrail** [comment]
<img width="1707" alt="Screenshot 2023-09-12 at 12 19 15 AM" src="https://github.com/sammcgrail/radarplot/assets/6109568/55551459-83f6-41d0-92a7-a2d354b78ab3">

Really odd, I'd wanna experiment with non strict mode and see if this api really is that laggy

**Comment by sammcgrail** [comment]
<img width="1728" alt="Screenshot 2023-09-12 at 7 25 27 PM" src="https://github.com/sammcgrail/radarplot/assets/6109568/73f48684-2bfd-467c-90b2-822416351435">


when disabling react strict mode - see the pane in top right quadrant, removed strict mode - - the network tab still shows two calls to: 

https://api.openweathermap.org/data/2.5/onecall?lat=42.3497567&lon=-71.1681248&appid=d1f7b4e1dc98b50318d89a9b72962deb&units=imperial&exclude=minutely

These seem to be identical -  can you try and debug this? Mike tried a bit but we'd like some support @br-ndt

**Comment by br-ndt** [comment]
@sammcgrail  @MichaelJOHare This is due to the effect's dependency array in `LocationContext`.

Because it is dependent on both the fetched fields (`geo` and `weather`, to be short), when `geo` is updated, the effect re-runs, causing `weather` to be fetched a second time (because in the render it is done a second time, its value has not yet been updated by the first render's fetch, so the `if (!data)` line in `fetchData.js` passes.

I would empty the dependency array on that effect, adding an ignore flag if your linter is bothered by it. There are other ways of first-render-only fetching besides using an effect but an effect is by far the simplest in React-land.
